
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point cs_n cs_n -type PI PI
add mapped point mosi mosi -type PI PI
add mapped point input_current[15] input_current[15] -type PI PI
add mapped point input_current[14] input_current[14] -type PI PI
add mapped point input_current[13] input_current[13] -type PI PI
add mapped point input_current[12] input_current[12] -type PI PI
add mapped point input_current[11] input_current[11] -type PI PI
add mapped point input_current[10] input_current[10] -type PI PI
add mapped point input_current[9] input_current[9] -type PI PI
add mapped point input_current[8] input_current[8] -type PI PI
add mapped point input_current[7] input_current[7] -type PI PI
add mapped point input_current[6] input_current[6] -type PI PI
add mapped point input_current[5] input_current[5] -type PI PI
add mapped point input_current[4] input_current[4] -type PI PI
add mapped point input_current[3] input_current[3] -type PI PI
add mapped point input_current[2] input_current[2] -type PI PI
add mapped point input_current[1] input_current[1] -type PI PI
add mapped point input_current[0] input_current[0] -type PI PI

//output ports
add mapped point miso miso -type PO PO
add mapped point spikes[2] spikes[2] -type PO PO
add mapped point spikes[1] spikes[1] -type PO PO
add mapped point spikes[0] spikes[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point nn_inst/spikes_layer_2[1]/q nn_inst/spikes_layer_2_reg_1_/Q -type DFF DFF
add mapped point nn_inst/spikes_layer_2[0]/q nn_inst/spikes_layer_2_reg_0_/Q -type DFF DFF
add mapped point nn_inst/spikes_layer_2[2]/q nn_inst/spikes_layer_2_reg_2_/Q -type DFF DFF
add mapped point reg_file/leak_reg[0]/q reg_file/leak_reg_reg_0_/Q -type DFF DFF
add mapped point reg_file/leak_reg[1]/q reg_file/leak_reg_reg_1_/Q -type DFF DFF
add mapped point reg_file/leak_reg[2]/q reg_file/leak_reg_reg_2_/Q -type DFF DFF
add mapped point reg_file/leak_reg[3]/q reg_file/leak_reg_reg_3_/Q -type DFF DFF
add mapped point reg_file/leak_reg[4]/q reg_file/leak_reg_reg_4_/Q -type DFF DFF
add mapped point reg_file/leak_reg[5]/q reg_file/leak_reg_reg_5_/Q -type DFF DFF
add mapped point reg_file/leak_reg[6]/q reg_file/leak_reg_reg_6_/Q -type DFF DFF
add mapped point reg_file/leak_reg[7]/q reg_file/leak_reg_reg_7_/Q -type DFF DFF
add mapped point reg_file/leak_reg[8]/q reg_file/leak_reg_reg_8_/Q -type DFF DFF
add mapped point reg_file/leak_reg[9]/q reg_file/leak_reg_reg_9_/Q -type DFF DFF
add mapped point reg_file/leak_reg[10]/q reg_file/leak_reg_reg_10_/Q -type DFF DFF
add mapped point reg_file/leak_reg[11]/q reg_file/leak_reg_reg_11_/Q -type DFF DFF
add mapped point reg_file/leak_reg[12]/q reg_file/leak_reg_reg_12_/Q -type DFF DFF
add mapped point reg_file/leak_reg[13]/q reg_file/leak_reg_reg_13_/Q -type DFF DFF
add mapped point reg_file/leak_reg[14]/q reg_file/leak_reg_reg_14_/Q -type DFF DFF
add mapped point reg_file/leak_reg[15]/q reg_file/leak_reg_reg_15_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[0]/q reg_file/refractory_reg_reg_0_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[1]/q reg_file/refractory_reg_reg_1_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[2]/q reg_file/refractory_reg_reg_2_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[3]/q reg_file/refractory_reg_reg_3_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[4]/q reg_file/refractory_reg_reg_4_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[5]/q reg_file/refractory_reg_reg_5_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[6]/q reg_file/refractory_reg_reg_6_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[7]/q reg_file/refractory_reg_reg_7_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[8]/q reg_file/refractory_reg_reg_8_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[9]/q reg_file/refractory_reg_reg_9_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[10]/q reg_file/refractory_reg_reg_10_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[11]/q reg_file/refractory_reg_reg_11_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[12]/q reg_file/refractory_reg_reg_12_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[13]/q reg_file/refractory_reg_reg_13_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[14]/q reg_file/refractory_reg_reg_14_/Q -type DFF DFF
add mapped point reg_file/refractory_reg[15]/q reg_file/refractory_reg_reg_15_/Q -type DFF DFF
add mapped point reg_file/reset_reg[0]/q reg_file/reset_reg_reg_0_/Q -type DFF DFF
add mapped point reg_file/reset_reg[1]/q reg_file/reset_reg_reg_1_/Q -type DFF DFF
add mapped point reg_file/reset_reg[2]/q reg_file/reset_reg_reg_2_/Q -type DFF DFF
add mapped point reg_file/reset_reg[3]/q reg_file/reset_reg_reg_3_/Q -type DFF DFF
add mapped point reg_file/reset_reg[4]/q reg_file/reset_reg_reg_4_/Q -type DFF DFF
add mapped point reg_file/reset_reg[5]/q reg_file/reset_reg_reg_5_/Q -type DFF DFF
add mapped point reg_file/reset_reg[6]/q reg_file/reset_reg_reg_6_/Q -type DFF DFF
add mapped point reg_file/reset_reg[7]/q reg_file/reset_reg_reg_7_/Q -type DFF DFF
add mapped point reg_file/reset_reg[8]/q reg_file/reset_reg_reg_8_/Q -type DFF DFF
add mapped point reg_file/reset_reg[9]/q reg_file/reset_reg_reg_9_/Q -type DFF DFF
add mapped point reg_file/reset_reg[10]/q reg_file/reset_reg_reg_10_/Q -type DFF DFF
add mapped point reg_file/reset_reg[11]/q reg_file/reset_reg_reg_11_/Q -type DFF DFF
add mapped point reg_file/reset_reg[12]/q reg_file/reset_reg_reg_12_/Q -type DFF DFF
add mapped point reg_file/reset_reg[13]/q reg_file/reset_reg_reg_13_/Q -type DFF DFF
add mapped point reg_file/reset_reg[14]/q reg_file/reset_reg_reg_14_/Q -type DFF DFF
add mapped point reg_file/reset_reg[15]/q reg_file/reset_reg_reg_15_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[0]/q reg_file/threshold_reg_reg_0_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[1]/q reg_file/threshold_reg_reg_1_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[2]/q reg_file/threshold_reg_reg_2_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[3]/q reg_file/threshold_reg_reg_3_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[4]/q reg_file/threshold_reg_reg_4_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[5]/q reg_file/threshold_reg_reg_5_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[6]/q reg_file/threshold_reg_reg_6_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[7]/q reg_file/threshold_reg_reg_7_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[8]/q reg_file/threshold_reg_reg_8_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[9]/q reg_file/threshold_reg_reg_9_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[10]/q reg_file/threshold_reg_reg_10_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[11]/q reg_file/threshold_reg_reg_11_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[12]/q reg_file/threshold_reg_reg_12_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[13]/q reg_file/threshold_reg_reg_13_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[14]/q reg_file/threshold_reg_reg_14_/Q -type DFF DFF
add mapped point reg_file/threshold_reg[15]/q reg_file/threshold_reg_reg_15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][0]/q reg_file/weight_mem_reg_0__0__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][1]/q reg_file/weight_mem_reg_0__0__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][2]/q reg_file/weight_mem_reg_0__0__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][3]/q reg_file/weight_mem_reg_0__0__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][4]/q reg_file/weight_mem_reg_0__0__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][5]/q reg_file/weight_mem_reg_0__0__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][6]/q reg_file/weight_mem_reg_0__0__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][7]/q reg_file/weight_mem_reg_0__0__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][8]/q reg_file/weight_mem_reg_0__0__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][9]/q reg_file/weight_mem_reg_0__0__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][10]/q reg_file/weight_mem_reg_0__0__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][11]/q reg_file/weight_mem_reg_0__0__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][12]/q reg_file/weight_mem_reg_0__0__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][13]/q reg_file/weight_mem_reg_0__0__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][14]/q reg_file/weight_mem_reg_0__0__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][0][15]/q reg_file/weight_mem_reg_0__0__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][0]/q reg_file/weight_mem_reg_0__1__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][1]/q reg_file/weight_mem_reg_0__1__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][2]/q reg_file/weight_mem_reg_0__1__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][3]/q reg_file/weight_mem_reg_0__1__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][4]/q reg_file/weight_mem_reg_0__1__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][5]/q reg_file/weight_mem_reg_0__1__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][6]/q reg_file/weight_mem_reg_0__1__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][7]/q reg_file/weight_mem_reg_0__1__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][8]/q reg_file/weight_mem_reg_0__1__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][9]/q reg_file/weight_mem_reg_0__1__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][10]/q reg_file/weight_mem_reg_0__1__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][11]/q reg_file/weight_mem_reg_0__1__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][12]/q reg_file/weight_mem_reg_0__1__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][13]/q reg_file/weight_mem_reg_0__1__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][14]/q reg_file/weight_mem_reg_0__1__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][1][15]/q reg_file/weight_mem_reg_0__1__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][0]/q reg_file/weight_mem_reg_0__2__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][1]/q reg_file/weight_mem_reg_0__2__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][2]/q reg_file/weight_mem_reg_0__2__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][3]/q reg_file/weight_mem_reg_0__2__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][4]/q reg_file/weight_mem_reg_0__2__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][5]/q reg_file/weight_mem_reg_0__2__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][6]/q reg_file/weight_mem_reg_0__2__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][7]/q reg_file/weight_mem_reg_0__2__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][8]/q reg_file/weight_mem_reg_0__2__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][9]/q reg_file/weight_mem_reg_0__2__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][10]/q reg_file/weight_mem_reg_0__2__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][11]/q reg_file/weight_mem_reg_0__2__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][12]/q reg_file/weight_mem_reg_0__2__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][13]/q reg_file/weight_mem_reg_0__2__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][14]/q reg_file/weight_mem_reg_0__2__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[0][2][15]/q reg_file/weight_mem_reg_0__2__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][0]/q reg_file/weight_mem_reg_1__0__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][1]/q reg_file/weight_mem_reg_1__0__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][2]/q reg_file/weight_mem_reg_1__0__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][3]/q reg_file/weight_mem_reg_1__0__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][4]/q reg_file/weight_mem_reg_1__0__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][5]/q reg_file/weight_mem_reg_1__0__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][6]/q reg_file/weight_mem_reg_1__0__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][7]/q reg_file/weight_mem_reg_1__0__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][8]/q reg_file/weight_mem_reg_1__0__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][9]/q reg_file/weight_mem_reg_1__0__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][10]/q reg_file/weight_mem_reg_1__0__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][11]/q reg_file/weight_mem_reg_1__0__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][12]/q reg_file/weight_mem_reg_1__0__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][13]/q reg_file/weight_mem_reg_1__0__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][14]/q reg_file/weight_mem_reg_1__0__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][0][15]/q reg_file/weight_mem_reg_1__0__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][0]/q reg_file/weight_mem_reg_1__1__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][1]/q reg_file/weight_mem_reg_1__1__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][2]/q reg_file/weight_mem_reg_1__1__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][3]/q reg_file/weight_mem_reg_1__1__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][4]/q reg_file/weight_mem_reg_1__1__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][5]/q reg_file/weight_mem_reg_1__1__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][6]/q reg_file/weight_mem_reg_1__1__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][7]/q reg_file/weight_mem_reg_1__1__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][8]/q reg_file/weight_mem_reg_1__1__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][9]/q reg_file/weight_mem_reg_1__1__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][10]/q reg_file/weight_mem_reg_1__1__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][11]/q reg_file/weight_mem_reg_1__1__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][12]/q reg_file/weight_mem_reg_1__1__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][13]/q reg_file/weight_mem_reg_1__1__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][14]/q reg_file/weight_mem_reg_1__1__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][1][15]/q reg_file/weight_mem_reg_1__1__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][0]/q reg_file/weight_mem_reg_1__2__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][1]/q reg_file/weight_mem_reg_1__2__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][2]/q reg_file/weight_mem_reg_1__2__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][3]/q reg_file/weight_mem_reg_1__2__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][4]/q reg_file/weight_mem_reg_1__2__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][5]/q reg_file/weight_mem_reg_1__2__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][6]/q reg_file/weight_mem_reg_1__2__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][7]/q reg_file/weight_mem_reg_1__2__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][8]/q reg_file/weight_mem_reg_1__2__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][9]/q reg_file/weight_mem_reg_1__2__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][10]/q reg_file/weight_mem_reg_1__2__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][11]/q reg_file/weight_mem_reg_1__2__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][12]/q reg_file/weight_mem_reg_1__2__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][13]/q reg_file/weight_mem_reg_1__2__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][14]/q reg_file/weight_mem_reg_1__2__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[1][2][15]/q reg_file/weight_mem_reg_1__2__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][0]/q reg_file/weight_mem_reg_2__0__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][1]/q reg_file/weight_mem_reg_2__0__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][2]/q reg_file/weight_mem_reg_2__0__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][3]/q reg_file/weight_mem_reg_2__0__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][4]/q reg_file/weight_mem_reg_2__0__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][5]/q reg_file/weight_mem_reg_2__0__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][6]/q reg_file/weight_mem_reg_2__0__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][7]/q reg_file/weight_mem_reg_2__0__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][8]/q reg_file/weight_mem_reg_2__0__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][9]/q reg_file/weight_mem_reg_2__0__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][10]/q reg_file/weight_mem_reg_2__0__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][11]/q reg_file/weight_mem_reg_2__0__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][12]/q reg_file/weight_mem_reg_2__0__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][13]/q reg_file/weight_mem_reg_2__0__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][14]/q reg_file/weight_mem_reg_2__0__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][0][15]/q reg_file/weight_mem_reg_2__0__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][0]/q reg_file/weight_mem_reg_2__1__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][1]/q reg_file/weight_mem_reg_2__1__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][2]/q reg_file/weight_mem_reg_2__1__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][3]/q reg_file/weight_mem_reg_2__1__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][4]/q reg_file/weight_mem_reg_2__1__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][5]/q reg_file/weight_mem_reg_2__1__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][6]/q reg_file/weight_mem_reg_2__1__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][7]/q reg_file/weight_mem_reg_2__1__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][8]/q reg_file/weight_mem_reg_2__1__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][9]/q reg_file/weight_mem_reg_2__1__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][10]/q reg_file/weight_mem_reg_2__1__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][11]/q reg_file/weight_mem_reg_2__1__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][12]/q reg_file/weight_mem_reg_2__1__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][13]/q reg_file/weight_mem_reg_2__1__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][14]/q reg_file/weight_mem_reg_2__1__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][1][15]/q reg_file/weight_mem_reg_2__1__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][0]/q reg_file/weight_mem_reg_2__2__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][1]/q reg_file/weight_mem_reg_2__2__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][2]/q reg_file/weight_mem_reg_2__2__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][3]/q reg_file/weight_mem_reg_2__2__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][4]/q reg_file/weight_mem_reg_2__2__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][5]/q reg_file/weight_mem_reg_2__2__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][6]/q reg_file/weight_mem_reg_2__2__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][7]/q reg_file/weight_mem_reg_2__2__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][8]/q reg_file/weight_mem_reg_2__2__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][9]/q reg_file/weight_mem_reg_2__2__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][10]/q reg_file/weight_mem_reg_2__2__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][11]/q reg_file/weight_mem_reg_2__2__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][12]/q reg_file/weight_mem_reg_2__2__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][13]/q reg_file/weight_mem_reg_2__2__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][14]/q reg_file/weight_mem_reg_2__2__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[2][2][15]/q reg_file/weight_mem_reg_2__2__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][0]/q reg_file/weight_mem_reg_3__0__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][1]/q reg_file/weight_mem_reg_3__0__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][2]/q reg_file/weight_mem_reg_3__0__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][3]/q reg_file/weight_mem_reg_3__0__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][4]/q reg_file/weight_mem_reg_3__0__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][5]/q reg_file/weight_mem_reg_3__0__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][6]/q reg_file/weight_mem_reg_3__0__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][7]/q reg_file/weight_mem_reg_3__0__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][8]/q reg_file/weight_mem_reg_3__0__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][9]/q reg_file/weight_mem_reg_3__0__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][10]/q reg_file/weight_mem_reg_3__0__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][11]/q reg_file/weight_mem_reg_3__0__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][12]/q reg_file/weight_mem_reg_3__0__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][13]/q reg_file/weight_mem_reg_3__0__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][14]/q reg_file/weight_mem_reg_3__0__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][0][15]/q reg_file/weight_mem_reg_3__0__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][0]/q reg_file/weight_mem_reg_3__1__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][1]/q reg_file/weight_mem_reg_3__1__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][2]/q reg_file/weight_mem_reg_3__1__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][3]/q reg_file/weight_mem_reg_3__1__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][4]/q reg_file/weight_mem_reg_3__1__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][5]/q reg_file/weight_mem_reg_3__1__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][6]/q reg_file/weight_mem_reg_3__1__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][7]/q reg_file/weight_mem_reg_3__1__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][8]/q reg_file/weight_mem_reg_3__1__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][9]/q reg_file/weight_mem_reg_3__1__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][10]/q reg_file/weight_mem_reg_3__1__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][11]/q reg_file/weight_mem_reg_3__1__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][12]/q reg_file/weight_mem_reg_3__1__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][13]/q reg_file/weight_mem_reg_3__1__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][14]/q reg_file/weight_mem_reg_3__1__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][1][15]/q reg_file/weight_mem_reg_3__1__15_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][0]/q reg_file/weight_mem_reg_3__2__0_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][1]/q reg_file/weight_mem_reg_3__2__1_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][2]/q reg_file/weight_mem_reg_3__2__2_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][3]/q reg_file/weight_mem_reg_3__2__3_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][4]/q reg_file/weight_mem_reg_3__2__4_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][5]/q reg_file/weight_mem_reg_3__2__5_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][6]/q reg_file/weight_mem_reg_3__2__6_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][7]/q reg_file/weight_mem_reg_3__2__7_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][8]/q reg_file/weight_mem_reg_3__2__8_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][9]/q reg_file/weight_mem_reg_3__2__9_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][10]/q reg_file/weight_mem_reg_3__2__10_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][11]/q reg_file/weight_mem_reg_3__2__11_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][12]/q reg_file/weight_mem_reg_3__2__12_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][13]/q reg_file/weight_mem_reg_3__2__13_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][14]/q reg_file/weight_mem_reg_3__2__14_/Q -type DFF DFF
add mapped point reg_file/weight_mem[3][2][15]/q reg_file/weight_mem_reg_3__2__15_/Q -type DFF DFF
add mapped point spi_inst/wr_en/q spi_inst/wr_en_reg/Q -type DFF DFF
add mapped point spi_inst/miso/q spi_inst/miso_reg/Q -type DFF DFF
add mapped point spi_inst/sclk_sync[1]/q spi_inst/sclk_sync_reg_1_/Q -type DFF DFF
add mapped point spi_inst/sclk_sync[0]/q spi_inst/sclk_sync_reg_0_/Q -type DFF DFF
add mapped point spi_inst/addr[0]/q spi_inst/addr_reg_0_/Q -type DFF DFF
add mapped point spi_inst/addr[1]/q spi_inst/addr_reg_1_/Q -type DFF DFF
add mapped point spi_inst/addr[2]/q spi_inst/addr_reg_2_/Q -type DFF DFF
add mapped point spi_inst/addr[3]/q spi_inst/addr_reg_3_/Q -type DFF DFF
add mapped point spi_inst/addr[4]/q spi_inst/addr_reg_4_/Q -type DFF DFF
add mapped point spi_inst/addr[5]/q spi_inst/addr_reg_5_/Q -type DFF DFF
add mapped point spi_inst/addr[6]/q spi_inst/addr_reg_6_/Q -type DFF DFF
add mapped point spi_inst/addr[7]/q spi_inst/addr_reg_7_/Q -type DFF DFF
add mapped point spi_inst/addr[8]/q spi_inst/addr_reg_8_/Q -type DFF DFF
add mapped point spi_inst/addr[9]/q spi_inst/addr_reg_9_/Q -type DFF DFF
add mapped point spi_inst/addr[10]/q spi_inst/addr_reg_10_/Q -type DFF DFF
add mapped point spi_inst/addr[11]/q spi_inst/addr_reg_11_/Q -type DFF DFF
add mapped point spi_inst/addr[12]/q spi_inst/addr_reg_12_/Q -type DFF DFF
add mapped point spi_inst/addr[13]/q spi_inst/addr_reg_13_/Q -type DFF DFF
add mapped point spi_inst/addr[14]/q spi_inst/addr_reg_14_/Q -type DFF DFF
add mapped point spi_inst/bit_count[0]/q spi_inst/bit_count_reg_0_/Q -type DFF DFF
add mapped point spi_inst/bit_count[1]/q spi_inst/bit_count_reg_1_/Q -type DFF DFF
add mapped point spi_inst/bit_count[2]/q spi_inst/bit_count_reg_2_/Q -type DFF DFF
add mapped point spi_inst/bit_count[3]/q spi_inst/bit_count_reg_3_/Q -type DFF DFF
add mapped point spi_inst/bit_count[4]/q spi_inst/bit_count_reg_4_/Q -type DFF DFF
add mapped point spi_inst/bit_count[5]/q spi_inst/bit_count_reg_5_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[0]/q spi_inst/read_buffer_reg_0_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[1]/q spi_inst/read_buffer_reg_1_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[2]/q spi_inst/read_buffer_reg_2_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[3]/q spi_inst/read_buffer_reg_3_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[4]/q spi_inst/read_buffer_reg_4_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[5]/q spi_inst/read_buffer_reg_5_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[6]/q spi_inst/read_buffer_reg_6_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[7]/q spi_inst/read_buffer_reg_7_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[8]/q spi_inst/read_buffer_reg_8_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[9]/q spi_inst/read_buffer_reg_9_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[10]/q spi_inst/read_buffer_reg_10_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[11]/q spi_inst/read_buffer_reg_11_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[12]/q spi_inst/read_buffer_reg_12_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[13]/q spi_inst/read_buffer_reg_13_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[14]/q spi_inst/read_buffer_reg_14_/Q -type DFF DFF
add mapped point spi_inst/read_buffer[15]/q spi_inst/read_buffer_reg_15_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[0]/q spi_inst/shift_reg_reg_0_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[1]/q spi_inst/shift_reg_reg_1_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[2]/q spi_inst/shift_reg_reg_2_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[3]/q spi_inst/shift_reg_reg_3_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[4]/q spi_inst/shift_reg_reg_4_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[5]/q spi_inst/shift_reg_reg_5_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[6]/q spi_inst/shift_reg_reg_6_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[7]/q spi_inst/shift_reg_reg_7_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[8]/q spi_inst/shift_reg_reg_8_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[9]/q spi_inst/shift_reg_reg_9_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[10]/q spi_inst/shift_reg_reg_10_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[11]/q spi_inst/shift_reg_reg_11_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[12]/q spi_inst/shift_reg_reg_12_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[13]/q spi_inst/shift_reg_reg_13_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[14]/q spi_inst/shift_reg_reg_14_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[15]/q spi_inst/shift_reg_reg_15_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[16]/q spi_inst/shift_reg_reg_16_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[17]/q spi_inst/shift_reg_reg_17_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[18]/q spi_inst/shift_reg_reg_18_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[19]/q spi_inst/shift_reg_reg_19_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[20]/q spi_inst/shift_reg_reg_20_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[21]/q spi_inst/shift_reg_reg_21_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[22]/q spi_inst/shift_reg_reg_22_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[23]/q spi_inst/shift_reg_reg_23_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[24]/q spi_inst/shift_reg_reg_24_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[25]/q spi_inst/shift_reg_reg_25_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[26]/q spi_inst/shift_reg_reg_26_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[27]/q spi_inst/shift_reg_reg_27_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[28]/q spi_inst/shift_reg_reg_28_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[29]/q spi_inst/shift_reg_reg_29_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[30]/q spi_inst/shift_reg_reg_30_/Q -type DFF DFF
add mapped point spi_inst/shift_reg[31]/q spi_inst/shift_reg_reg_31_/Q -type DFF DFF
add mapped point spi_inst/state[0]/q spi_inst/state_reg_0_/Q -type DFF DFF
add mapped point spi_inst/state[1]/q spi_inst/state_reg_1_/Q -type DFF DFF
add mapped point spi_inst/wr_data[0]/q spi_inst/wr_data_reg_0_/Q -type DFF DFF
add mapped point spi_inst/wr_data[1]/q spi_inst/wr_data_reg_1_/Q -type DFF DFF
add mapped point spi_inst/wr_data[2]/q spi_inst/wr_data_reg_2_/Q -type DFF DFF
add mapped point spi_inst/wr_data[3]/q spi_inst/wr_data_reg_3_/Q -type DFF DFF
add mapped point spi_inst/wr_data[4]/q spi_inst/wr_data_reg_4_/Q -type DFF DFF
add mapped point spi_inst/wr_data[5]/q spi_inst/wr_data_reg_5_/Q -type DFF DFF
add mapped point spi_inst/wr_data[6]/q spi_inst/wr_data_reg_6_/Q -type DFF DFF
add mapped point spi_inst/wr_data[7]/q spi_inst/wr_data_reg_7_/Q -type DFF DFF
add mapped point spi_inst/wr_data[8]/q spi_inst/wr_data_reg_8_/Q -type DFF DFF
add mapped point spi_inst/wr_data[9]/q spi_inst/wr_data_reg_9_/Q -type DFF DFF
add mapped point spi_inst/wr_data[10]/q spi_inst/wr_data_reg_10_/Q -type DFF DFF
add mapped point spi_inst/wr_data[11]/q spi_inst/wr_data_reg_11_/Q -type DFF DFF
add mapped point spi_inst/wr_data[12]/q spi_inst/wr_data_reg_12_/Q -type DFF DFF
add mapped point spi_inst/wr_data[13]/q spi_inst/wr_data_reg_13_/Q -type DFF DFF
add mapped point spi_inst/wr_data[14]/q spi_inst/wr_data_reg_14_/Q -type DFF DFF
add mapped point spi_inst/wr_data[15]/q spi_inst/wr_data_reg_15_/Q -type DFF DFF



//Black Boxes
add mapped point nn_inst/layer_1_neurons[0].neuron_layer_1 nn_inst/layer_1_neurons_0__neuron_layer_1 -type BBOX BBOX
add mapped point nn_inst/layer_1_neurons[1].neuron_layer_1 nn_inst/layer_1_neurons_1__neuron_layer_1 -type BBOX BBOX
add mapped point nn_inst/layer_1_neurons[2].neuron_layer_1 nn_inst/layer_1_neurons_2__neuron_layer_1 -type BBOX BBOX
add mapped point nn_inst/layer_1_neurons[3].neuron_layer_1 nn_inst/layer_1_neurons_3__neuron_layer_1 -type BBOX BBOX
add mapped point nn_inst/layer_2_neurons[0].neuron_layer_2 nn_inst/layer_2_neurons_0__neuron_layer_2 -type BBOX BBOX
add mapped point nn_inst/layer_2_neurons[1].neuron_layer_2 nn_inst/layer_2_neurons_1__neuron_layer_2 -type BBOX BBOX
add mapped point nn_inst/layer_2_neurons[2].neuron_layer_2 nn_inst/layer_2_neurons_2__neuron_layer_2 -type BBOX BBOX



//Empty Modules as Blackboxes
